In [1]:
import numpy as np
import matplotlib.pyplot as plt
# https://github.com/MouseLand/suite2p/issues/166
# https://suite2p.readthedocs.io/_/downloads/en/latest/pdf/

In [2]:
STATS_FILENAME = 'D:/OneDrive - Duke University/RRR增量备份/Grad/Rotation/LG_lab/local_run/stat.npy'
st = np.load(STATS_FILENAME, allow_pickle=True)
n_rois = st.shape[0]
height = 264; width = 796 # Image size in pixels
mask = np.zeros((n_rois, height, width))

for i in range(n_rois):
    mask[i, st[i]['ypix'], st[i]['xpix']] = st[i]['lam']

In [3]:
n_rois

2685

In [4]:
mask.shape

(2685, 264, 796)

In [ ]:
# find out why mask is not digital

In [13]:
plt.figure(figsize=(20,10))
plt.imshow(mask[100])

In [28]:
type(mask)

numpy.ndarray

In [31]:
mask_all = sum(mask,1)
plt.figure(figsize=(20,10))
plt.imshow(mask_all)

In [10]:
plt.hist(mask[100]);
plt.xlim([0,0.004]);

In [12]:
sum(sum(mask[100] > 0.0035))

64

In [7]:
plt.hist(mask[1]);

In [7]:
i=1
mask[i, st[i]['ypix'], st[i]['xpix']] 

array([0.00332807, 0.00419319, 0.00296805, 0.00362532, 0.00615833,
       0.00762292, 0.00810862, 0.00888546, 0.00652746, 0.0068442 ,
       0.01194239, 0.01389441, 0.012763  , 0.01156076, 0.00894433,
       0.00302201, 0.00932135, 0.01540534, 0.0178531 , 0.01733898,
       0.01720219, 0.01286201, 0.00462462, 0.00370349, 0.01135221,
       0.01697955, 0.02166846, 0.02515738, 0.02484499, 0.0173627 ,
       0.00589962, 0.0051672 , 0.01329717, 0.02122185, 0.02954673,
       0.03463935, 0.03186349, 0.02173899, 0.00768653, 0.00443094,
       0.01501888, 0.02457776, 0.03808748, 0.04737796, 0.03889605,
       0.02426093, 0.00757035, 0.00258785, 0.01066073, 0.02312563,
       0.04116468, 0.05115289, 0.036012  , 0.02012333, 0.0051911 ,
       0.00459325, 0.01204034, 0.02177342, 0.02381748, 0.01532222,
       0.00842809, 0.0031379 , 0.00342295, 0.00532092, 0.00477904])

In [9]:
st[i]['ypix']

array([158, 158, 158, 159, 159, 159, 159, 159, 159, 160, 160, 160, 160,
       160, 160, 160, 161, 161, 161, 161, 161, 161, 161, 162, 162, 162,
       162, 162, 162, 162, 162, 163, 163, 163, 163, 163, 163, 163, 163,
       164, 164, 164, 164, 164, 164, 164, 164, 165, 165, 165, 165, 165,
       165, 165, 165, 166, 166, 166, 166, 166, 166, 166, 167, 167, 167])

In [9]:
st[i]['xpix']

array([538, 538, 540, 541, 542, 543, 538, 539, 540, 541, 542, 543, 538,
       539, 540, 541, 542, 543, 544, 537, 538, 539, 540, 541, 542, 543,
       544, 545, 546, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547,
       535, 537, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 537,
       541, 542, 543, 544, 546])